/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking;

import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Kopano
 */
public class beneficiariess extends javax.swing.JFrame {
        private JTable table;
        private DefaultTableModel model;
        private JButton btnBack, btnDelete;

    public beneficiariess() {
        setTitle("My Beneficiaries");
        setSize(750, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);   

        // ---------- TABLE MODEL ----------
        model = new DefaultTableModel(
            new Object[]{"Name", "Account Number", "Branch Code", "Bank Name"},
            0
        );

        // ---------- TABLE ----------
        table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setBounds(20, 20, 700, 350);
        add(scrollPane);

        // ---------- DELETE SELECTED BUTTON ----------
        btnDelete = new JButton("Delete Selected");
        btnDelete.setBounds(20, 390, 150, 40);
        btnDelete.addActionListener(e -> deleteSelected());
        add(btnDelete);

        // ---------- BACK BUTTON ----------
        btnBack = new JButton("Back to Dashboard");
        btnBack.setBounds(560, 390, 160, 40);
        btnBack.addActionListener(e -> goBack());
        add(btnBack);

        // Load data
        loadBeneficiaries();
    }

    private void goBack() {
        new dashborad().setVisible(true);
        dispose();
    }

    // ---------------- DELETE SELECTED BENEFICIARY ----------------
    private void deleteSelected() {
        int row = table.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a beneficiary first.");
            return;
        }

        // Get account number from table
        String accNumber = model.getValueAt(row, 1).toString();
        String email = Session.getEmail();

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this beneficiary?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        try (Connection conn = DatabaseConnection.getConnection()) {

            PreparedStatement ps = conn.prepareStatement(
                "DELETE FROM beneficiaries WHERE account_number = ? AND user_email = ?"
            );

            ps.setString(1, accNumber);
            ps.setString(2, email);

            int affected = ps.executeUpdate();

            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "Beneficiary deleted successfully!");
                loadBeneficiaries(); // refresh table
            } else {
                JOptionPane.showMessageDialog(this, "Error: Beneficiary not found.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }

    // ---------------- LOAD BENEFICIARIES ----------------
    private void loadBeneficiaries() {
        String email = Session.getEmail();
        if (email == null) {
            JOptionPane.showMessageDialog(this, "User not logged in!");
            return;
        }

        model.setRowCount(0);

        try (Connection conn = DatabaseConnection.getConnection()) {

            PreparedStatement ps = conn.prepareStatement(
                "SELECT name, account_number, branch_code, bank_name FROM beneficiaries WHERE user_email = ?"
            );

            ps.setString(1, email);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("name"),
                    rs.getString("account_number"),
                    rs.getString("branch_code"),
                    rs.getString("bank_name")
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beneficiariess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beneficiariess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beneficiariess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beneficiariess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beneficiariess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
