 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Sibusiso
 */
public class PRICES extends javax.swing.JFrame {
    private String selectNetwork="";
    private double selectedAmount=0.0;

    /**
     * Creates new form PRICES
     */
    public PRICES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectedLabel = new javax.swing.JTextField();
        labelNext = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn10 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn100 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn200 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Purchase Amount");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insert the Amount you want");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        selectedLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(selectedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 160, 40));

        labelNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNext.setForeground(new java.awt.Color(255, 255, 255));
        labelNext.setText("Next");
        labelNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNextMouseClicked(evt);
            }
        });
        jPanel1.add(labelNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn10.setForeground(new java.awt.Color(0, 0, 204));
        btn10.setText("R10");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, 30));
        btn10.getAccessibleContext().setAccessibleDescription("");

        btn20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn20.setForeground(new java.awt.Color(0, 0, 204));
        btn20.setText("R20");
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        jPanel1.add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 100, 30));
        btn20.getAccessibleContext().setAccessibleDescription("");

        btn25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn25.setForeground(new java.awt.Color(0, 0, 204));
        btn25.setText("R25");
        btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ActionPerformed(evt);
            }
        });
        jPanel1.add(btn25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));
        btn25.getAccessibleContext().setAccessibleDescription("");

        btn100.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn100.setForeground(new java.awt.Color(0, 0, 204));
        btn100.setText("R100");
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });
        jPanel1.add(btn100, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 30));
        btn100.getAccessibleContext().setAccessibleDescription("");

        btn30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn30.setForeground(new java.awt.Color(0, 0, 204));
        btn30.setText("R30");
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });
        jPanel1.add(btn30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 100, 30));
        btn30.getAccessibleContext().setAccessibleDescription("");

        btn200.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn200.setForeground(new java.awt.Color(0, 0, 204));
        btn200.setText("R200");
        btn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200ActionPerformed(evt);
            }
        });
        jPanel1.add(btn200, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 100, 30));
        btn200.getAccessibleContext().setAccessibleDescription("");

        btn50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn50.setForeground(new java.awt.Color(0, 0, 204));
        btn50.setText("R50");
        btn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50ActionPerformed(evt);
            }
        });
        jPanel1.add(btn50, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 100, 30));
        btn50.getAccessibleContext().setAccessibleDescription("");

        btn500.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn500.setForeground(new java.awt.Color(0, 0, 204));
        btn500.setText("R500");
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });
        jPanel1.add(btn500, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 100, 30));
        btn500.getAccessibleContext().setAccessibleDescription("");

        btn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn5.setForeground(new java.awt.Color(0, 0, 204));
        btn5.setText("R5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));
        btn5.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new purchase().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void labelNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNextMouseClicked
        // TODO add your handling code here:
         if (selectedAmount == 0 ) {
        JOptionPane.showMessageDialog(this, "Please select an amount and first.");
        return;
    }

    String email = Session.getEmail();
    if (email == null || email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please log in first.");
        new login11().setVisible(true);
        dispose();
        return;
    }

    try (Connection conn = DatabaseConnection.getConnection()) {
        // Get user balance
        String sql = "SELECT balance FROM users WHERE email = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, email);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            double balance = rs.getDouble("balance");

            if (balance >= selectedAmount) {
                double newBalance = balance - selectedAmount;

                // Update balance
                String updateSQL = "UPDATE users SET balance = ? WHERE email = ?";
                PreparedStatement updatePS = conn.prepareStatement(updateSQL);
                updatePS.setDouble(1, newBalance);
                updatePS.setString(2, email);
                updatePS.executeUpdate();

                // Generate random airtime PIN (10 digits)
                String airtimePin = generateRandomPin(10);

                JOptionPane.showMessageDialog(this, 
                    "Airtime purchase successful!\n" +
                    "Amount: R" + selectedAmount + "\n" +
                    "PIN: " + airtimePin + "\n\nThank you!"
                );

                // Optional: reset selection
                selectedAmount = 0;
                selectedLabel.setText("No airtime selected. ");
                

            } else {
                JOptionPane.showMessageDialog(this, "Insufficient balance for this purchase.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "User not found.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

}
    private String generateRandomPin(int length) {
    String digits = "0123456789";
    StringBuilder pin = new StringBuilder();
    java.util.Random random = new java.util.Random();

    for (int i = 0; i < length; i++) {
        pin.append(digits.charAt(random.nextInt(digits.length())));
    }
    return pin.toString();

      
    }//GEN-LAST:event_labelNextMouseClicked

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        // TODO add your handling code here:
        selectedAmount=50;
        selectedLabel.setText("Selected: "+ "R "+ selectedAmount);
        
    }//GEN-LAST:event_btn500ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        selectedAmount=5;
        selectedLabel.setText("Selected: "+ "R "+ selectedAmount);
        
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ActionPerformed
        // TODO add your handling code here:
        selectedAmount=25;
        selectedLabel.setText("Selected: "+ "R "+ selectedAmount);
        
    }//GEN-LAST:event_btn25ActionPerformed

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        // TODO add your handling code here:
        selectedAmount=100;
        selectedLabel.setText("Selected: "+ "R "+ selectedAmount);
        
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        selectedAmount=10;
        selectedLabel.setText("Selected: "+ "R "+ selectedAmount);
        
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed
        // TODO add your handling code here:
        selectedAmount=30;
        selectedLabel.setText("Selected: "+ "R "+ selectedAmount);
        
    }//GEN-LAST:event_btn30ActionPerformed

    private void btn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200ActionPerformed
        // TODO add your handling code here:
        selectedAmount=200;
        selectedLabel.setText("Selected: "+ "R "+ selectedAmount);
        
    }//GEN-LAST:event_btn200ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
        selectedAmount=20;
        selectedLabel.setText("Selected: "+ "R "+ selectedAmount);
        
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50ActionPerformed
        // TODO add your handling code here:
        selectedAmount=50;
        selectedLabel.setText("Selected: "+ "R "+ selectedAmount);
        
    }//GEN-LAST:event_btn50ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRICES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn500;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNext;
    private javax.swing.JTextField selectedLabel;
    // End of variables declaration//GEN-END:variables
}
